### ISSUE TITLE
German translation not valid

### ISSUE THREAD

**Issue by tomka75** [MicrosoftDocs/powerapps-docs.de-de#2]
Hi,

for STRG + X, C, and V the translations are not valid in German. Here the shortcut, the automatic translation and the correct German words.

STRG + X | Schnitts.|Ausschneiden
STRG + C | Skopie.|Kopieren
STRG + V | Kle.|Einfügen

BR
Tomislav Karafilov

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 955cb34a-35ce-b369-a83b-b68195de2a63
* Version Independent ID: e7503f23-33ab-2a1a-6796-ea6d96b64146
* Content: [Tastenkombinationen für Canvas-apps - PowerApps](https://docs.microsoft.com/de-de/powerapps/maker/canvas-apps/keyboard-shortcuts#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerapps-docs.de-de/blob/live/powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by srvbpigh** [comment]
Hello, @tomka75
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @tomka75 

Vielen Dank für Ihr Feedback. Die betroffene Seite wurde maschinenübersetzt. Daher kann es sein, dass der Inhalt nicht immer verständlich ist. Wir haben vor Kurzem die Option „Read in English“ (Auf Englisch lesen) rechts hinzugefügt, sodass Sie zur englischen Version wechseln können, ohne die Spracheinstellungen ändern zu müssen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
